# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # deps
  - package-ecosystem: npm
    target-branch: 'master'
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
    directory: /
    commit-message:
      prefix: 'deps'
  # dev-deps
  - package-ecosystem: npm
    schedule:
      interval: weekly
    allow:
      - dependency-type: development
    directory: /
    commit-message:
      prefix: 'devdeps'
    groups:
      types:
        patterns:
          - '@types/*'
      dev-patch:
        update-types:
          - patch

  # github deps
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: 'ci'
    directory: '/'
